export const START_FETCHING_CHECKOUTS = "redux/events/START_FETCHING_CHECKOUTS";
export const SUCCESS_FETCHING_CHECKOUTS =
  "redux/events/SUCCESS_FETCHING_CHECKOUTS";
export const ERROR_FETCHING_CHECKOUTS = "redux/events/ERROR_FETCHING_CHECKOUTS";
export const SET_PAGE = "redux/orders/SET_PAGE";
