export const START_FETCHING_CHECKOUTS = "redux/checkouts/START_FETCHING_CHECKOUTS";
export const SUCCESS_FETCHING_CHECKOUTS =
  "redux/checkouts/SUCCESS_FETCHING_CHECKOUTS";
export const ERROR_FETCHING_CHECKOUTS = "redux/checkouts/ERROR_FETCHING_CHECKOUTS";
