export const START_FETCHING_LISTS_DEPARTEMENT =
  "redux/lists/START_FETCHING_LISTS_DEPARTEMENT";
export const SUCCESS_FETCHING_LISTS_DEPARTEMENT =
  "redux/lists/SUCCESS_FETCHING_LISTS_DEPARTEMENT";
export const ERROR_FETCHING_LISTS_DEPARTEMENT =
  "redux/lists/ERROR_FETCHING_LISTS_DEPARTEMENT";

export const START_FETCHING_LISTS_GROUP =
  "redux/lists/START_FETCHING_LISTS_GROUP";
export const SUCCESS_FETCHING_LISTS_GROUP =
  "redux/lists/SUCCESS_FETCHING_LISTS_GROUP";
export const ERROR_FETCHING_LISTS_GROUP =
  "redux/lists/ERROR_FETCHING_LISTS_GROUP";

export const START_FETCHING_LISTS_USER =
  "redux/lists/START_FETCHING_LISTS_USER";
export const SUCCESS_FETCHING_LISTS_USER =
  "redux/lists/SUCCESS_FETCHING_LISTS_USER";
export const ERROR_FETCHING_LISTS_USER =
  "redux/lists/ERROR_FETCHING_LISTS_USER";
